#!/bin/bash
# QUICKSTART GUIDE FOR RASPBERRY PI 4B
# =====================================

echo "LearnFlow - Raspberry Pi Deployment Quick Start"
echo "================================================"
echo ""
echo "STEP 1: Transfer files to your Raspberry Pi"
echo "-------------------------------------------"
echo "Option A - Using SCP (from your computer):"
echo "  tar -czf learnflow.tar.gz ."
echo "  scp learnflow.tar.gz pi@raspberrypi.local:~/"
echo ""
echo "Option B - Using USB drive:"
echo "  1. Copy all files to USB drive"
echo "  2. Insert USB into Raspberry Pi"
echo "  3. Copy files: cp -r /media/usb/* ~/learnflow/"
echo ""
echo "STEP 2: SSH into Raspberry Pi"
echo "-----------------------------"
echo "  ssh pi@raspberrypi.local"
echo "  (default password is usually 'raspberry')"
echo ""
echo "STEP 3: Extract and navigate"
echo "---------------------------"
echo "  cd ~"
echo "  tar -xzf learnflow.tar.gz -C learnflow"
echo "  cd learnflow"
echo ""
echo "STEP 4: Run the deployment script"
echo "--------------------------------"
echo "  chmod +x deploy.sh"
echo "  ./deploy.sh"
echo ""
echo "STEP 5: Access your app!"
echo "-----------------------"
echo "  From Raspberry Pi: http://localhost:3000"
echo "  From other devices: http://[raspberry-pi-ip]:3000"
echo ""
echo "To find your Raspberry Pi IP:"
echo "  hostname -I"
echo ""
echo "================================================"
echo ""
echo "USEFUL COMMANDS:"
echo "  docker-compose logs -f     # View logs"
echo "  docker-compose restart     # Restart app"
echo "  docker-compose down        # Stop app"
echo "  docker-compose up -d       # Start app"
echo ""
